'use client';

import Header from '@/components/Header';
import { ExtensionProvider } from '@/context/ExtensionContext';
import { notosans } from '@/styles/fonts';
import '@/styles/globals.css';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={`${notosans.className} font-bold antialiased bg-linear-(--gradient) min-h-screen pt-6`}>
        <div className='mx-4 xs:mx-8 lg:mx-12 xl:max-w-[1170px] xl:mx-auto'>
          <Header />
          <ExtensionProvider>{children}</ExtensionProvider>
        </div>
      </body>
    </html>
  );
}
