import Header from '@/components/Header';
import { notosans } from '@/styles/fonts';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={`${notosans.className} font-bold antialiased bg-linear-(--gradient) min-h-screen pt-6`}>
        <div className='mx-4 sm:mx-8 md:mx-auto md:max-w-[704px] lg:mx-[135px] lg:max-w-[1170px]'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
